global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'iris_api'
    static_configs:
      - targets: ['api:5000']  # Use service name, not localhost

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
